In [2]:
import tensorflow as tf

2025-05-24 19:17:05.233285: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
# Tạo tensor từ list
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
print("Shape:", tensor.shape)  # Kích thước các chiều (row, col)
print("Type:", tensor.dtype)  # Kiểu dữ liệu
print("Rank:", tensor.ndim)  # Số chiều

Shape: (3, 2)
Type: <dtype: 'int32'>
Rank: 2


In [ ]:
# Khởi tạo tensor zeros
zeros = tf.zeros([2, 3])
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
# Khởi tạo tensor ones
ones = tf.ones([3, 2])
print(ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
# Khởi tạo tensor với giá trị ngẫu nhiên
random = tf.random.normal([2, 2], mean=0.0, stddev=1.0)
print(random)

tf.Tensor(
[[ 1.1322191  -1.1053851 ]
 [-0.12569472  2.1446824 ]], shape=(2, 2), dtype=float32)


In [ ]:
# Type Casting (Chuyển đổi kiễu dữ liệu)
float_tensor = tf.constant([1.0, 2.0])
int_tensor = tf.cast(float_tensor, tf.int32)
print(float_tensor)
print(int_tensor)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
# Indexing & Slicing
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
# Lấy phần tử tại hàng 1, cột 2
elem = tensor[1, 2]
print(elem)

# Lấy slice
slice = tensor[:, 1:]  # Lấy tất cả các hàng, từ cột 1 trở đi
print(slice)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


In [ ]:
# Math Operation
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Cộng element
add = tf.add(a, b)
print(add)

# Nhân element-wise
mul = tf.multiply(a, b)
print(mul)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
