In [5]:
import numpy as np

a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]])
cong = a + b
tru = a - b
print(cong)
print(tru)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [6]:
c = np.array([[2,-3],[4,-5]]) 
d = np.array([[1,4],[-2,6]])
tong = np.add(c,d)
hieu = np.subtract(c,d)
print(tong)
print(hieu)

[[3 1]
 [2 1]]
[[  1  -7]
 [  6 -11]]


In [8]:
hadamard = a * b
print(hadamard)

[[ 5 12]
 [21 32]]


In [9]:
e = np.array([[0,1,2],[3,4,5]])
f = np.array([[5,4,3],[2,1,0]])
hadamard_ef = e * f
print(hadamard_ef)

[[0 4 6]
 [6 4 0]]


In [13]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
dot_product = np.dot(v1, v2.T)
print(dot_product)

32


In [19]:
#convolution
a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
k = np.array([[1,0],[0,-1]])

def convolution(mat, kernel):
    rows = mat.shape[0] - kernel.shape[0] + 1
    cols = mat.shape[1] - kernel.shape[1] + 1
    result = np.zeros((rows, cols))

    for i in range(rows):
        for j in range(cols):
            result[i,j] = np.sum(mat[i:i+2, j:j+2] * kernel)
    
    return result

result = convolution(a1, k)
print(result)

[[-4. -4.]
 [-4. -4.]]


In [20]:
vec_a = np.array([1, 0])

def rotate(v, degree):
    rotated = np.array([[np.cos(degree), -np.sin(degree)],
                        [np.sin(degree), np.cos(degree)]])
    return v.dot(rotated)

print(rotate(vec_a, 45))


[ 0.52532199 -0.85090352]
