GramMatrix with Numpy

In [ ]:
import numpy as np

def compute_gram_matrix(feature_map : np.ndarray) -> np.ndarray:
    #Lấy kích thước đầu vào
    C, H, W = feature_map.shape
    # Chuyển đổi ma trận về dạng C, H*W
    F = feature_map.reshape(C, H*W)
    # Tính Gram matrix G = F @ F.T
    G = np.dot(F, F.T)
    # Chuẩn hóa bằng số điểm ảnh
    G /= (H * W)
    return G

np.random.seed(42)
feature_map = np.random.rand(3, 4, 4)
gram_matrix = compute_gram_matrix(feature_map)

print(gram_matrix)

[[0.33432857 0.2207897  0.27598961]
 [0.2207897  0.19580158 0.19452994]
 [0.27598961 0.19452994 0.32603015]]


GramMatrix with Torch

In [ ]:
import torch

In [6]:
feature_map_torch = torch.tensor(feature_map, dtype=torch.float32)
F_torch = feature_map_torch.view(3, -1)
gram_matrix_torch = torch.mm(F_torch, F_torch.t()) / (4 * 4)

print("\nGram Matrix PyTorch:\n", gram_matrix_torch.numpy())


Gram Matrix PyTorch:
 [[0.33432856 0.2207897  0.2759896 ]
 [0.2207897  0.19580159 0.19452995]
 [0.2759896  0.19452995 0.32603014]]


In [16]:
def compute_gram_matrix(feature_map : np.ndarray) -> np.ndarray:
    C, H, W = feature_map.shape
    F = feature_map.reshape(C, H * W).astype(np.float64)
    G = np.dot(F, F.T)
    G /= (H * W)
    return G

feature_map = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

#Tính Gram matrix
gram_matrix = compute_gram_matrix(feature_map)
print(gram_matrix)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]


Similarity with Numpy 
So sánh độ tương đồng giữa hai ảnh bằng Gram Matrix

In [22]:
def compute_similarity(gram1: np.ndarray, gram2: np.ndarray) -> float:
    numerator = np.sum(gram1 * gram2)
    denominator = np.sqrt(np.sum(gram1**2)) * np.sqrt(np.sum(gram2**2))
    return numerator/denominator

#Feature map của 2 ảnh
feature_map1 = np.array([
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        [[9,10],[11,12]]
        ])  
feature_map2 = np.array([
        [[2,4],[6,8]],
        [[1,3],[5,7]],
        [[0,2],[4,6]]
        ])  

gram1 = compute_gram_matrix(feature_map1)
gram2 = compute_gram_matrix(feature_map2)
result = compute_similarity(gram1, gram2)
print(result)

0.6741245785155123
